### PR TITLE
Issue_4: Created CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by edilsalvador**
# Pull Request

**Github Issue Number Link:** [*#4*](https://github.com/tekilinux/TekiLinux-amd64/issues/4)

**GitHub Branch Link:** [*edilsalvador/TekiLinux-amd64/Issue_4*](https://github.com/edilsalvador/TekiLinux-amd64/tree/Issue_4)

## Description
- *Included in this Pull Request is the Contributing file for anyone who wants to contribute.*

## Changes
- *Added `CONTRIBUTING.md`*
- *Initial tasks completed:*
*- *Introduction**
*- *Issue tracker**
*- *Bug reporting**
*- *Feature requests**
*- *Pull requests**
*- *other concerns**

## Relevant Issues
- *Suggestions are openly welcome! :smile:*

## Place to start
- *Look at `CONTRIBUTING.md`*
- *After merging this pull request eventually the contributing prompt will show every time someone will create an issue.*

The prompt would look like this:
image

### CODE REVIEW

**Comment by edilsalvador** [comment]
[#5 ⁃ Issue_4: Created CONTRIBUTING.md](https://trello.com/c/0WSaQEeT/5-5-issue4-created-contributingmd)

**Review by apquinit — APPROVED** [review]
nice documentation! thanks edil!

**Comment by apquinit** [comment]
I suggest putting CONTRIBUTING.md in the root folder based on this github standard: https://github.com/blog/1184-contributing-guidelines.

**Comment by edilsalvador** [comment]
Yeah, I think it should be placed on the root folder so anyone can already see it :+1:

**Comment by apquinit** [comment]
Don't forget to delete /.github directory! :)

I think we can merge it now. So that ronel can follow the guide. He's on his first PR now.

**Comment by edilsalvador** [comment]
I guess .github directory could stay. The pull request template is placed there.

**Comment by apquinit** [comment]
update the bullet under "Place to Start". delete first line

**Comment by edilsalvador** [comment]
Already fixed that :smile:

**Comment by apquinit** [comment]
MERGEEE!!! :) :) :)

**Comment by apquinit** [comment]
close PR

**Pull request merged**
